package View;

import Controller.ControllerPacote;
import Controller.ControllerServico;
import Model.Pacote;
import Model.Servicos;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import util.Util;
import static View.frmFrontOffice.cmbxServico;
import static View.frmFrontOffice.cmbxPacote;

/**
 *
 * @author Jay
 */
public class frmConfigPacotes extends JFrame {

    private Pacote pacote;
    private Servicos servicos;
    
    private final ControllerPacote controllerPacote;
    private final ControllerServico controllerServico;

    /**
     * Creates new form frmCliente
     */
    public frmConfigPacotes() {
        initComponents();
        controllerPacote = new ControllerPacote();
        controllerServico = new ControllerServico();
        setLocationRelativeTo(null);
        ListarServicos();
    }
    
    public void ListarServicos() {
        try {
            //String com o usuario do banco de dados
            String usuario = "root";
            //String com o caminho do banco de daods
            String url = "jdbc:mysql://localhost:3306/sgps";
            //String com a senha do banco de daods
            String senha = "";
            Connection conexao = DriverManager.getConnection(url, usuario, senha);

            //Query que traz os dados do banco de dados
            String sql = "SELECT * FROM servicos";

            //Prepara para executar um comando
            PreparedStatement pst = conexao.prepareStatement(sql);

            //Armazena o resultado da consulta
            ResultSet rs = pst.executeQuery();

            //Enquanto existirem dados executa o laco de repeticao
            while (rs.next()) {
                jCServicos.addItem(String.valueOf(rs.getString("NomeDoServico")));
            }

        } catch (SQLException e) {
            //Rastreia o erro
            e.printStackTrace();
        }

    }
        
        
            public void ListarPacotes(String idServicos) {
        try {
            //String com o usuario do banco de dados
            String usuario = "root";
            //String com o caminho do banco de daods
            String url = "jdbc:mysql://localhost:3306/sgps";
            //String com a senha do banco de daods
            String senha = "";
            Connection conexao = DriverManager.getConnection(url, usuario, senha);

            //Query que traz os dados do banco de dados
            String sql = "SELECT * FROM pacote where servicos_idServicos=?";

            //Prepara para executar um comando
            PreparedStatement pst = conexao.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(idServicos));
            //Armazena o resultado da consulta
            ResultSet rs = pst.executeQuery();

            //Enquanto existirem dados executa o laco de repeticao
            while (rs.next()) {
                cmbxPacote.addItem(String.valueOf(rs.getString("NomeDoPacote")));
            }

        } catch (SQLException e) {
            //Rastreia o erro
            e.printStackTrace();
        }
    }

    private Pacote salvarPacote() throws NumberFormatException {

        String Desc = JTDesc.getText();
        if (this.pacote == null) {
            this.pacote = new Pacote(servicos, Desc);
        } else {
            this.pacote.setNomeDoPacote(Desc);
            this.pacote.setServicos(controllerServico.findByName("nomeDoServico", jCServicos.getSelectedItem() + ""));
        }
        return this.pacote;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jxBtSave = new org.jdesktop.swingx.JXButton();
        jxBtSave1 = new org.jdesktop.swingx.JXButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        JTDesc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCServicos = new javax.swing.JComboBox<>();

        setTitle("Configuracao de Pacotes");

        jxBtSave.setBackground(new java.awt.Color(255, 255, 255));
        jxBtSave.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.orange));
        jxBtSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/glyphicons-444-floppy-disk.png"))); // NOI18N
        jxBtSave.setToolTipText("Gravar registo...");
        jxBtSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxBtSaveActionPerformed(evt);
            }
        });

        jxBtSave1.setBackground(new java.awt.Color(255, 255, 255));
        jxBtSave1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.orange));
        jxBtSave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/glyphicons-436-undo.png"))); // NOI18N
        jxBtSave1.setToolTipText("Gravar registo...");
        jxBtSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxBtSave1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Descrição");

        jLabel2.setText("Serviço");

        jCServicos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCServicosItemStateChanged(evt);
            }
        });
        jCServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCServicosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCServicos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(142, 142, 142))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JTDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCServicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dados Principais", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jxBtSave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jxBtSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane1)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jxBtSave, jxBtSave1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jxBtSave, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jxBtSave1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jxBtSave, jxBtSave1});

        pack();
    }// </editor-fold>                        

    private void jxBtSaveActionPerformed(java.awt.event.ActionEvent evt) {                                         
        controllerPacote.save(salvarPacote());
    }                                        

    private void jxBtSave1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jCServicosItemStateChanged(java.awt.event.ItemEvent evt) {                                            
//JtCodigo.setText(jCServicos.getSelectedItem().toString());
    }                                           

    private void jCServicosActionPerformed(java.awt.event.ActionEvent evt) {                                           
            
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmConfigPacotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmConfigPacotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmConfigPacotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmConfigPacotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmConfigPacotes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField JTDesc;
    public static javax.swing.JComboBox<String> jCServicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private org.jdesktop.swingx.JXButton jxBtSave;
    private org.jdesktop.swingx.JXButton jxBtSave1;
    // End of variables declaration                   

}
