package Model;
// Generated Oct 8, 2017 3:40:37 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Contratos generated by hbm2java
 */
@Entity
@Table(name="contratos"
    ,catalog="sgps"
)
public class Contratos  implements java.io.Serializable {


     private Integer idContratos;
     private Cliente cliente;
     private Servicos servicos;
     private String tipodecontrato;

    public Contratos() {
    }

	
    public Contratos(Cliente cliente, Servicos servicos) {
        this.cliente = cliente;
        this.servicos = servicos;
    }
    public Contratos(Cliente cliente, Servicos servicos, String tipodecontrato) {
       this.cliente = cliente;
       this.servicos = servicos;
       this.tipodecontrato = tipodecontrato;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idContratos", unique=true, nullable=false)
    public Integer getIdContratos() {
        return this.idContratos;
    }
    
    public void setIdContratos(Integer idContratos) {
        this.idContratos = idContratos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Cliente_idCliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="servicos_idServicos", nullable=false)
    public Servicos getServicos() {
        return this.servicos;
    }
    
    public void setServicos(Servicos servicos) {
        this.servicos = servicos;
    }

    
    @Column(name="tipodecontrato", length=45)
    public String getTipodecontrato() {
        return this.tipodecontrato;
    }
    
    public void setTipodecontrato(String tipodecontrato) {
        this.tipodecontrato = tipodecontrato;
    }




}


