package Model;
// Generated Oct 8, 2017 3:40:37 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pagamento generated by hbm2java
 */


@Entity
@Table(name = "pagamento", catalog = "sgps"
)
public class Pagamento implements java.io.Serializable {

    private Integer idPagamento;
    private String nomeCliente;
    private String servico;
    private String pacote;
    private Date datapag;
    private double valorpago;

    public Pagamento() {
    }

    public Pagamento(String nomeCliente, Date dataDePagamento, String pacote, String servico, double valorPago) {
        this.nomeCliente = nomeCliente;
        this.datapag = dataDePagamento;
        this.pacote = pacote;
        this.servico = servico;
        this.valorpago = valorPago;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idPagamento", unique = true, nullable = false)
    public Integer getIdPagamento() {
        return this.idPagamento;
    }

    public void setIdPagamento(Integer idPagamento) {
        this.idPagamento = idPagamento;
    }

    @Column(name = "nomeCliente", nullable = false)
    public String getCliente() {
        return this.nomeCliente;
    }

    public void setCliente(String nomeCliente) {
        this.nomeCliente = nomeCliente;
    }

    @Column(name = "Servico", nullable = false, length = 200)
    public String getServico() {
        return this.servico;
    }

    public void setServico(String servico) {
        this.servico = servico;
    }

    @Column(name = "Pacote", nullable = false, length = 200)
    public String getPacote() {
        return this.pacote;
    }

    public void setPacote(String pacote) {
        this.pacote = pacote;
    }


    @Temporal(TemporalType.DATE)
    @Column(name = "datapag", nullable = false, length = 10)
    public Date getDatapag() {
        return this.datapag;
    }

    public void setDatapag(Date datapag) {
        this.datapag = datapag;
    }

    @Column(name = "valorpago", nullable = false)
    public double getValorpago() {
        return this.valorpago;
    }

    public void setValorpago(double valor) {
        this.valorpago = valor;
    }

    public double calculaDivida() {
        long dias = (new Date().getTime() - datapag.getTime()) / (24 * 60 * 60 * 1000);
        System.out.println("" + dias);
        return dias > 0 ? dias * 200 : 0.0;
    }

}
